version: '3.1'

services:

#  #####################
#  # NGINX Config for applications
#  #####################
#  nginx:
#    image: nginx:latest
#    container_name: production_nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./certs:/certs
#    ports:
#      - 80:80
#      - 443:443

  #####################
  # POSTGRES
  # Contaions the database for the applications
  #####################
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  ###################
  # MAILHOG
  # Captures email for development
  ###################
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
